### ISSUE TITLE
Scheduler calls Pycos.peer() with incorrect params

### ISSUE THREAD

**Issue by skozlovf** [pgiri/pycos#10]
If pass `nodes` to `Scheduler` then it fails with:
```
Scheduler(..., nodes=[...])
```

```
Traceback (most recent call last):
  File ".../site-packages/pycos/__init__.py", line 3611, in _schedule
    retval = task._generator.send(task._value)
  File ".../site-packages/pycos/dispycos.py", line 1243, in __computation_scheduler_proc
    yield self.pycos.peer(node, broadcast=True)
TypeError: peer() got an unexpected keyword argument 'broadcast'
```

https://github.com/pgiri/pycos/blob/d632087ac1cac7652daf9d58e630db324a5731e2/py2/pycos/dispycos.py#L1243

`peer()` has no `broadcast` argument:
https://github.com/pgiri/pycos/blob/d632087ac1cac7652daf9d58e630db324a5731e2/py2/pycos/netpycos.py#L342

**Comment by pgiri** [comment]
`peer` method's `broadcast` has been renamed to 'relay` (quit) sometime ago, but this case apparently was not renamed! I am debating whether to simply drop 'relay' here or may be add an option so user can decide to use relay or not. I will commit a fix soon; in the meantime, can you just remove `, broadcast=True` in your tree?

**Comment by skozlovf** [comment]
Sure, thanks!
