### ISSUE TITLE
Non-local nodes doesn't execute tasks

### ISSUE THREAD

**Issue by skozlovf** [pgiri/pycos#11]
I have one remote node in external network, reachable from my PC. But it can't run tasks.

Here is code I run locally:

```python
import pycos
import random
from pycos.dispycos import Scheduler, Computation, Task
from pycos.netpycos import Pycos, Location

def compute(n, task=None):
    yield task.sleep(0.1)
    raise StopIteration((n, task.location))


def client(njobs, task=None):
    p = Pycos.instance()
    loc = Location('Y.Y.Y.Y', 9706)
    status = yield p.peer(loc, udp_port=9706, task=task)
    print('STATUS %s' % status)

    computation = Computation([compute])

    if (yield computation.schedule()):
        raise Exception('Could not schedule computation')

    args = [random.uniform(2, 5) for _ in range(njobs)]
    res = yield computation.run_result(compute, args)
    print('Results: {}'.format(res))

    yield computation.close()


if __name__ == '__main__':
    pycos.logger.setLevel(pycos.logger.DEBUG)
    Scheduler(node='192.168.1.82', ext_ip_addr='X.X.X.X', discover_peers=False)
    Task(client, 2)
```

On remote node I run:
```
$ dispycosnode.py -i 192.168.5.168 --cpus  1 --daemon --debug --clean --ext_ip_addr Y.Y.Y.Y
```

`192.168.1.82` - my local IP, I'm connected to Inet via router.
`X.X.X.X` - my external IP.
`192.168.5.168` - remote node local IP  (it's an AWS instance).
`Y.Y.Y.Y` - remote node external IP.

Local log after running above code:
```
2018-11-27 17:04:39 dispycos - version 4.8.6 with epoll I/O notifier
2018-11-27 17:04:39 dispycos - TCP server "dispycos_scheduler" @ X.X.X.X:9705
2018-11-27 17:04:39 dispycos - UDP server @ <broadcast>:9705
2018-11-27 17:04:39 dispycos - waiting for 1 tasks to terminate
2018-11-27 17:04:40 dispycos - X.X.X.X:9705: found peer Y.Y.Y.Y:9706
STATUS 0
2018-11-27 17:04:40 dispycos - Computation 36c0a69799ed3162206467fd33a5d683ca171d9f / da362d3bbadd08a54e7bcd2ef76dd3d65fedfa04 scheduled

<waits forever>
```

Remote `dispycosnode.py` output:
```
2018-11-27 10:46:44 dispycosnode - version 4.8.6 with epoll I/O notifier
2018-11-27 10:46:44 dispycosnode - TCP server "ip-192-168-5-168_server-0" @ Y.Y.Y.Y:9706
2018-11-27 10:46:44 dispycosnode - UDP server @ <broadcast>:9706
2018-11-27 10:46:56 dispycosnode - Y.Y.Y.Y:9706: found peer X.X.X.X:9705
```

Looks like `dispycosnode` connects with my PC but nothing happens after that.

This code works fine if client and node runs in the same network.
Anything I can do here? Thanks.

**Comment by pgiri** [comment]
Instead of dispycos, can you try simpler example first. Attached are slight modifications of `remote_task_*.py` that should work (adjust IP address / name in examples as necessary).

```python
import sys
import pycos
# import netpycos to use add networking to Pycos
import pycos.netpycos

def receiver(task=None):
    task.set_daemon()
    task.register('server_task')
    while True:
        msg = yield task.receive()
        print('Received %s' % msg)

pycos.logger.setLevel(pycos.Logger.DEBUG)
config = {
    'node': ['192.168.1.82'],
    'ext_ip_addr': ['ext.ip.addr'],
    'udp_port': 9705,
    'tcp_port': 9705,
}

scheduler = pycos.Pycos(**config)

task = pycos.Task(receiver)
task.send(task)
task.send(str(task))
if sys.version_info.major > 2:
    read_input = input
else:
    read_input = raw_input
while True:
    try:
        cmd = read_input().strip().lower()
        if cmd in ('quit', 'exit'):
            break
    except:
        break
```
The above is `remote_task_server.py` that should be run on local computer.

``python
import pycos
# import netpycos to use add networking to Pycos
import pycos.netpycos

def sender(task=None):
    # if server is in remote network, add it; set 'stream_send' to
    # True for streaming messages to it
    yield scheduler.peer(pycos.Location('ext.ip.addr', port=9705))
    rtask = yield pycos.Task.locate('server_task', timeout=10)
    print('server is at %s' % rtask.location)
    for x in range(5):
        rtask.send('message %s' % task)

pycos.logger.setLevel(pycos.Logger.DEBUG)
config = {
    # 'node': ['192.168.5.168'],
    'node': ['ec2.ext.ip'],
    'tcp_port': 9706,
    'udp_port': 9706,
}

pycos.Pycos(**config)
pycos.Task(sender).value()
```
Above is `remote_task_client.py` that should be run on EC2 (remote) server.

If the above works, then may be you need to start dispycosnode with EC2 external IP address (e.g., `dispycosnode.py --ip_addr ec2.ext.ip`. If the above doesn't work, then you may need to configure your router (`X.X.X.X` in above example) to forward 9705 port to your computer at `192.168.1.82`. You also need to configure EC2 setup to allow incoming traffic at port 9706 (from your local computer IP). There is more documentation at [dispy Cloud Computing](http://dispy.sourceforge.net/dispy.html#cloud-computing) that may be helpful.

If you get all this working, it would be great if you can post a simple working example so it can be included in future release.

**Comment by skozlovf** [comment]
As you suggested it was permissions issue. In once case master (client) server blocked traffic from nodes. In another case with home PC I configured port forwarding in the router and increased nodes discovery timeout.

In your `remote_task_client.py` I replaced:
```python
yield scheduler.peer(pycos.Location('ext.ip.addr', port=9705))
```

with
```python
p = pycos.Pycos.instance()
yield p.peer(pycos.Location('ext.ip.addr', 9705))
```

> If you get your program (cloud computing with EC2) working, it would be great if you can post a simple working example so it can be included in future release.

Ok, I'll post something useful.

Thank you for your help.
