### ISSUE TITLE
Zombie nodes

### ISSUE THREAD

**Issue by skozlovf** [pgiri/pycos#12]
I run remote tasks on servers which may go down. And I want to reschedule such tasks later on new or idle nodes. So trying to understand how `pycos` handles zombie nodes.

The case.
I start one node locally:
```
$ dispycosnode.py -d --debug -c 1 --max_pulse_interval 10 --clean --daemon
```
Then run scheduler and send remote task to the node, then kill the node.

After some timeout it calls `Scheduler.__close_node()`, then `Scheduler.__close_server()`. The latter hangs forever. Because it waits remote tasks to finish (waits for `server.cpu_avail` event):

https://github.com/pgiri/pycos/blob/master/py2/pycos/dispycos.py#L1698-L1699

But remote task can't be finished since parent node is down already. Is it expected behavior?

I tried the following way: I start manual timer with timeout lower than zombie one, move node's server to disabled and close peer:
```python

def _timer_proc(self, task=None):
    ...
    node = self.scheduler._nodes.get(msg.location.addr)
    if node:
        node.disabled_servers.update(node.servers)
        node.servers.clear()
    yield self.scheduler.pycos.close_peer(loc)
```

this forces scheduler thinks what node's server is disconnected. And it notifies listener with statuses: `ServerAbandoned`, `ServerDisconnected`, `ServerClosed`, `NodeClosed`. Which can be used to handle the case.

Is there more correct way? Or maybe you could give me advice where to look in `pycos` sources?
Thank you.

**Comment by pgiri** [comment]
I think fix committed just now should handle this case. I haven't tested it though.

I am not sure if you are trying to change dispycos.py implementation. I don't think this is necessary - current timer and zombie handing should work. If not, let me know what is not working or your plans on changes so I can offer help / clarify.

dispycos doesn't deal with faults (i.e., it doesn't resubmit tasks elsewhere etc.) but this can be implemented with status notification messages. I have tried to add fault-tolerance (quite) sometime ago, but have abandoned it (for now).

**Comment by skozlovf** [comment]
Looks like it works now.

> I am not sure if you are trying to change dispycos.py implementation.

I try to use it without modifications where possible. And seems it provides all necessary features for now.

> I have tried to add fault-tolerance (quite) sometime ago, but have abandoned it (for now).

Well, workflows may be different and the lib is pretty low level. So maybe leave implementation to users, `dispycos` provides useful notifications for that.
