### ISSUE TITLE
Weird MemoryError gets masked by another exception in handler code

### ISSUE THREAD

**Issue by n00bmind** [pgiri/pycos#28]
I'm seeing this problem in a long-running server task:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/zentrade/venv/zentrade/lib/python3.7/site-packages/pycos/__init__.py", line 3671, in _schedule
    retval = task._generator.send(task._value)
  File "/home/zentrade/venv/zentrade/lib/python3.7/site-packages/pycos/__init__.py", line 899, in _async_recv_msg
    data = yield self.recvall(n)
  File "/home/zentrade/venv/zentrade/lib/python3.7/site-packages/pycos/__init__.py", line 504, in _async_recvall
    self._read_result = bytearray(bufsize)
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zentrade/venv/zentrade/lib/python3.7/site-packages/pycos/__init__.py", line 3705, in _schedule
    if type(exc[1].args[0]) == GeneratorExit:
IndexError: tuple index out of range
```

The MemoryError by itself is pretty strange. Running 'top' in the server machine shows my process using on the order of 3% of total system memory, so I have no idea where that's coming from.

Moving past that though, I think the second issue is even more relevant, as looking at the source code it seems to be happening inside the handling code for the first exception and preventing it from being added to the task._exceptions list, and thus from giving my user code a chance to detect or handle the issue in any useful way.

It seems to me from just having a quick look that the code at that line shold be checking exc[1].args in a similar way as the previous cases for StopIteration and HotSwapException are already doing.

**Comment by pgiri** [comment]
Is it possible that the program may be receiving large buffer (this exception happens in `recvall`)? Perhaps the sender has more memory than at the receiver? (The receiver allocates given size buffer to store data and if that chunk is not available, it is likely `MemoryError` is thrown? I am guessing this part.) Is it possible to attach programs / snippets that caused this error?

**Comment by pgiri** [comment]
Even if 'top` may show program not using much memory, it may have been misleading, as by the time `top` takes a snapshot, the issue may have already happened and system freed up memory. With the fix committed above, you can now handle `MemoryError` to show size of the buffer being received into and likely alter the program accordingly.

**Comment by n00bmind** [comment]
Thanks for the prompt reply.
Well, the messages I'm sending to the server are pretty simple json-serialized requests, so they should be really just a few bytes, certainly nothing that could ever cause the machine to run out of memory.
I'll continue gathering info if I see this happen again.

Thanks for the commited fix, any idea when this will make it to the next pip release?

**Comment by pgiri** [comment]
Next release will likely be either this week or coming weekend. I am waiting for feedback on some updates to dispycos module. In the meantime, if you want to use above fix, it is easy to prepare pip package yourself and install; see [installation](https://pycos.sourceforge.io/#download-installation) on how to install github source.

**Comment by n00bmind** [comment]
Many thanks.
I'll keep an eye on the MemoryError thing and open a new issue if I manage to gather more info.
I think we can close this now.
