### ISSUE TITLE
Cannot launch multiple computations

### ISSUE THREAD

**Issue by gobbedy** [pgiri/pycos#8]
Hello,

I am currently blocked in my use of dispy (see https://github.com/pgiri/dispy/issues/143), so I've tried to refactor my code to use pycos.

I've run into a different blocking issue.

I am unable to launch a second Computation. I've tried all sorts of workarounds and tricks and I cannot get past this issue.

Below is a standalone that reproduces the issue:

```python

import pycos.netpycos as pycos
from pycos.dispycos import *

def node_available(avail_info, data_file, task=None):
    import os
    # 'node_available' is executed locally (at client) when a node is
    # available. 'location' is Location instance of node. When this task is
    # executed, 'depends' of computation would've been transferred.

    # data_file could've been sent with the computation 'depends'; however, to
    # illustrate how files can be sent separately (e.g., to transfer different
    # files to different nodes), file is transferred with 'node_available'.

    print('  Sending %s to %s' % (data_file, avail_info.location.addr))
    sent = yield pycos.Pycos().send_file(avail_info.location, data_file,
                                         overwrite=True, timeout=5)
    if (sent < 0):
        print('Could not send data file "%s" to %s' % (data_file, avail_info.location))
        raise StopIteration(-1)

    # value of task (last value yield'ed or value of 'raise StopIteration') will
    # be passed to node_setup as argument(s).
    yield computation.enable_node(avail_info.location.addr, data_file)

def node_setup(data_file):
    # 'node_setup' is executed on a node with the arguments returned by
    # 'node_available'. This task should return 0 to indicate successful
    # initialization.

    # variables declared as 'global' will be available (as read-only) in tasks.
    global os, hashlib, data, file_name
    import os, hashlib
    # note that files transferred to node are in parent directory of cwd where
    # each computation is run (in case such files need to be accessed in
    # computation).
    print('data_file: "%s"' % data_file)
    with open(data_file, 'rb') as fd:
        data = fd.read()
    os.remove(data_file)  # data_file is not needed anymore
    file_name = data_file
    yield 0  # task must have at least one 'yield' and 0 indicates success

# 'compute' is executed at remote server process repeatedly to compute checksum
# of data in memory, initialized by 'node_setup'
def compute(alg, n, task=None):
    global data, hashlib
    yield task.sleep(n)
    checksum = getattr(hashlib, alg)()
    checksum.update(data)
    raise StopIteration((file_name, alg, checksum.hexdigest()))

# local task to process status messages from scheduler
def status_proc(task=None):
    task.set_daemon()
    i = 0
    while 1:
        msg = yield task.receive()
        if not isinstance(msg, DispycosStatus):
            continue
        if msg.status == Scheduler.NodeDiscovered:
            pycos.Task(node_available, msg.info.avail_info, data_file)
            i += 1

def client_proc(computation, task=None):
    if (yield computation.schedule()):
        raise Exception('Could not schedule computation')

    # execute 10 jobs (tasks) and get their results. Note that number of jobs
    # created can be more than number of server processes available; the
    # scheduler will use as many processes as necessary/available, running one
    # job at a server process
    yield task.sleep(2)
    algorithms = ['md5', 'sha1', 'sha224', 'sha256', 'sha384', 'sha512']
    args = [(algorithms[i % len(algorithms)], random.uniform(1, 3)) for i in range(15)]
    results = yield computation.run_results(compute, args)
    for i, result in enumerate(results):
        if isinstance(result, tuple) and len(result) == 3:
            print('   %ssum for %s: %s' % (result[1], result[0], result[2]))
        else:
            print('  rtask failed for %s: %s' % (args[i][0], str(result)))

    yield computation.close()


if __name__ == '__main__':
    import logging, random, functools, sys, os, glob
    # pycos.logger.setLevel(pycos.Logger.DEBUG)
    if os.path.dirname(sys.argv[0]):
        os.chdir(os.path.dirname(sys.argv[0]))
    # if scheduler is not already running (on a node as a program),
    # start private scheduler:
    Scheduler()

    data_file = 'test.txt'

    # Since this example doesn't work with Windows, 'node_allocations' feature
    # is used to filter out nodes running Windows.
    node_allocations = [DispycosNodeAllocate(node='*', platform='Windows', cpus=0)]
    computation = Computation([compute], node_allocations=node_allocations,
                              status_task=pycos.Task(status_proc), node_setup=node_setup,
                              disable_nodes=True)
    pycos.Task(client_proc, computation)


    # TRY LAUNCHING A NEW COMPUTATION
    Scheduler(clean=True)
    computation2 = Computation([compute], node_allocations=node_allocations,
                              status_task=pycos.Task(status_proc), node_setup=node_setup,
                              disable_nodes=True)
    pycos.Task(client_proc, computation2)

```

The code above gives this error:

> 2018-09-03 11:24:05 dispycos - version 4.8.0 with epoll I/O notifier
> 2018-09-03 11:24:06 dispycos - TCP server "dispycos_scheduler" @ 206.12.124.6:9705
> 2018-09-03 11:24:06 dispycos - UDP server @ <broadcast>:9705
> 2018-09-03 11:24:06 dispycos - uncaught exception in !_schedule/140470142127976:
> Traceback (most recent call last):
>   File "/home/gobbedy/.local/lib/python3.6/site-packages/pycos/__init__.py", line 3667, in _schedule
>     retval = task._generator.send(task._value)
>   File "/home/gobbedy/.local/lib/python3.6/site-packages/pycos/dispycos.py", line 285, in _schedule
>     SysTask.scheduler().atexit(10, lambda: SysTask(self.close))
>   File "/home/gobbedy/.local/lib/python3.6/site-packages/pycos/__init__.py", line 3941, in atexit
>     i = bisect_left(self._atexit, item)
> TypeError: '<' not supported between instances of 'function' and 'function'
> 
> 2018-09-03 11:24:06 dispycos - uncaught exception in !client_proc/140470142127624:
> Traceback (most recent call last):
>   File "/home/gobbedy/.local/lib/python3.6/site-packages/pycos/__init__.py", line 3667, in _schedule
>     retval = task._generator.send(task._value)
>   File "dispy_example.py", line 579, in client_proc
>     raise Exception('Could not schedule computation')
> Exception: Could not schedule computation

Note that in my real code 'node_setup' is different for the second computation, hence why I need different computations.

Thanks in advance for your help!

Regards,
Guillaume.

**Comment by pgiri** [comment]
dispycos doesn't allow more than one client to run simultaneously. Close currently running computation before submitting another computation. Unlike with dispy, dispycos allows any function (not just the one used to create `Computation` instance, or any sent with dependents) to be sent to nodes, so it is not necessary to create new computation just to run different function.

**Comment by gobbedy** [comment]
Thank you @pgiri,

Could you give me an example of how to send a function to nodes? It's easy enough using node_setup but I'm not sure how to send a function after the fact to be run on all nodes.

**Comment by pgiri** [comment]
I don't think I understand the question clearly. If you are asking how to run a function on the servers (once node_setup is finished no changes can be done at the node level, but servers retain state until computation is closed, so you can send any function to affect the state of each server). See documentation for `run_at`, `run`,  `run_result`, `run_async_at` etc. You can, e.g.,  get list of all nodes / servers with `nodes` or `servers` method and run a task on each. Changes done at that server with that task will be available to future computations on that server until computation is closed.

See `dispycos_client4.py` where `rtask_proc` is sent to server although it is not sent in with `Computation`.

**Comment by gobbedy** [comment]
Ah perfect, thanks an image is worth a thousand words and an example is worth a thousand images! Haha. I'll take a look, although I may try your new dispy code first. :)

**Comment by gobbedy** [comment]
I've got my code working with dispy now. I think pycos is overkill for my application, and the learning curve for me to figure out pycos properly would be rather steeper than dispy. So I'll only get back to this if needed. Thanks as always for your help.
